version: "3.8"

services:
  ubuntu-container:
    build: .
    container_name: ubuntu-container
    privileged: true
    volumes:
      - ./books:/home/ansible/books
      - /var/run/docker.sock:/var/run/docker.sock
    working_dir: /home/ansible
    stdin_open: true  
    tty: true   
    ports:
      - "8080:80"
      - "3000:3000"     
    
    entrypoint: ["/bin/sh"]
  jenkins:
    build: 
      context: .
      dockerfile: Dockerfile.jenkins
    container_name: jenkins_2
    ports:
      - "9090:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    privileged: true
    restart: always
volumes:
  jenkins_home:
