---
- name: cron setup
  hosts: ubuntu
  become: true

  tasks:
    - name: install cron
      apt:
        name: cron
        state: present
        update_cache: yes
    
    - name: start cron
      service:
        name: cron
        state: started
        enabled: yes
    - name: create a job
      cron:
        name: auto update
        job: apt update && apt upgrade -y
        minute: 0
        hour: 0