---
- name: install monitoring tools
  hosts: ubuntu
  become: true

  tasks:
    - name: install prometheus and grafana
      apt:
        name: 
          - prometheus
          - grafana
        state: present
    - name: start prometheus and grafana
      systemd:
        name: 
          - prometheus
          - grafana
        state: started
        enabled: true
    - name: configure ports
      ufw:
        rule: allow
        port:
          - 9090
          - 3000