---
- name: install monitoring tools
  hosts: ubuntu
  become: yes

  tasks:
    - name: install git
      apt:
        name: git
        state: present
        update_cache: yes
    - name: clone ansible-prometheus repo
      git:
        repo: https://github.com/cloudalchemy/ansible-prometheus.git
        dest: /tmp/ansible/prometheus
    - name: create directory structure
      file:
        path: /tmp/ansiible-prometheus/roles/cloudalchemy.prometheus
        state: directory
    - name: copy files
      command:
        cmd: mv defaults/ handlers/ meta/ molecule/ tasks/ templates/ vars/ /tmp/ansible-prometheus/roles/cloudalchemy.prometheus/
        chdir: /tmp/ansible-prometheus

    - name: copy main.yml
      copy:
        dest: /tmp/ansible-prometheus/roles/cloudalchemy.prometheus/main.yml
        src: main.yml

    - name: run playbook
      command:
        cmd: ansible-playbook /tmp/ansible/roles/cloudalchemy.prometheus/main.yml